- name: Create an EC2 key
  ec2_key:
    name: "{{ ssh_key }}"
    region: "{{ region }}"
  register: ec2_key

- name: save private key
  copy:
    content: "{{ ec2_key.key.private_key }}" 
    dest: "./aws_sg_demo_private.pem" 
    mode: 0600
  when: ec2_key.changed
